theme: jekyll-theme-minimal
title: Holly Kennedy
description: Digital forensics and more
author.name: Holly Kennedy
author.email: contact@hollykennedy.me
show_downloads: false
google_analytics: G-6QBNNDYF8P
excerpt_separator: <!--more-->